# Changes here will be overwritten by Copier
_commit: v1.5.4
_src_path: https://github.com/Tecnativa/doodba-copier-template.git
backup_deletion: false
backup_dst: s3://s3.amazonaws.com/example-bkp
backup_email_from: backup@example.com
backup_email_to: alerts@example.com
backup_tz: UTC
cidr_whitelist: null
domain_prod: www.example.com
domain_prod_alternatives:
  - example.com
domain_test: test.example.com
gitlab_url: https://gitlab.com/example/doodba-devel-master
odoo_dbfilter: .*
odoo_initial_lang: ""
odoo_listdb: true
odoo_oci_image: docker.io/myuser/myproject-odoo
odoo_proxy: traefik
odoo_version: 13.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_username: odoo
postgres_version: 12
project_author: Tecnativa
project_license: BSL-1.0
project_name: doodba-devel-master
smtp_canonical_default: example.com
smtp_canonical_domains:
  - example.com
smtp_default_from: ""
smtp_relay_host: smtp.example.com
smtp_relay_port: 587
smtp_relay_user: postmaster@example.com
