# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.0-5-gaab7e9d
_src_path: https://github.com/moduon/doodba-copier-template.git
backup_deletion: false
backup_dst: s3://s3.amazonaws.com/example-bkp
backup_email_from: backup@example.com
backup_email_to: alerts@example.com
backup_image_version: latest
backup_tz: UTC
cidr_whitelist: null
domains_prod:
  - cert_resolver: letsencrypt
    hosts:
      - www.example.com
  - cert_resolver: letsencrypt
    hosts:
      - example.com
    redirect_to: www.example.com
domains_test:
  - cert_resolver: letsencrypt
    hosts:
      - test.example.com
gitlab_url: https://gitlab.com/example/doodba-devel-13.0
odoo_dbfilter: .*
odoo_initial_lang: ""
odoo_listdb: false
odoo_oci_image: docker.io/myuser/myproject-odoo
odoo_proxy: traefik
odoo_version: 13.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_username: odoo
postgres_version: "10"
project_author: Tecnativa
project_license: BSL-1.0
project_name: doodba-devel-13.0
smtp_canonical_default: example.com
smtp_canonical_domains:
  - example.com
smtp_default_from: ""
smtp_relay_host: smtp.example.com
smtp_relay_port: 587
smtp_relay_user: postmaster@example.com
smtp_relay_version: "9.0"
