# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v3.0.0
_src_path: https://github.com/Tecnativa/doodba-copier-template.git
backup_deletion: false
backup_dst: ""
backup_email_from: backup@example.com
backup_email_to: alerts@example.com
backup_image_version: latest
backup_tz: UTC
cidr_whitelist: null
domains_prod: []
domains_test: []
gitlab_url: ""
odoo_dbfilter: .*
odoo_initial_lang: en_US
odoo_listdb: true
odoo_oci_image: ""
odoo_proxy: traefik
odoo_version: 14.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_username: odoo
postgres_version: "13"
project_author: Jairo Llopis
project_license: BSL-1.0
project_name: doodba-devel
smtp_canonical_default: example.com
smtp_canonical_domains:
  - example.com
smtp_default_from: ""
smtp_relay_host: ""
smtp_relay_port: 587
smtp_relay_user: postmaster@example.com
smtp_relay_version: "9.0"
